services:
  portainer:
    image: portainer/portainer-ce:latest

    container_name: portainer

    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/data/portainer:/data

    networks:
      - tar-cloud

networks:
  tar-cloud:
    external: true