services:
  portainer:
    image: portainer/portainer-ce:latest

    container_name: portainer

    restart: unless-stopped

    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.external-url=/prometheus
      - --web.route-prefix=/

    volumes:
      - /srv/data/prometheus:/prometheus
      - /srv/tar-cloud-infra/compose/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

    networks:
      - tar-cloud

networks:
  tar-cloud:
    external: true