---
services:
  cloudflared:
    image: cloudflare/cloudflared:latest

    container_name: cloudflared

    restart: unless-stopped

    env_file:
      - .env

    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}

    networks:
      - tar-cloud

networks:
  tar-cloud:
    external: true
