services:
  redis:
    image: redis:8

    container_name: redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - /srv/data/redis:/data

    command: >
      redis-server
      --appendonly yes

    networks:
      - tar-cloud

networks:
  tar-cloud:
    external: true
