services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage

    restart: unless-stopped

    env_file:
      - /srv/docker/env/tar-cloud.env

    volumes:
      - /srv/tar-cloud-infra/compose/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro

    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*"

    networks:
      - tar-cloud

networks:
  tar-cloud:
    external: true
