services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage

    restart: unless-stopped

    volumes:
      - /srv/tar-cloud-infra/compose/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro

    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*"
      HOMEPAGE_VAR_GRAFANA_USERNAME: ${GRAFANA_USERNAME}
      HOMEPAGE_VAR_GRAFANA_PASSWORD: ${GRAFANA_PASSWORD}

      HOMEPAGE_VAR_PORTAINER_TOKEN: ${PORTAINER_TOKEN}

      HOMEPAGE_VAR_MINIO_USERNAME: ${MINIO_USERNAME}
      HOMEPAGE_VAR_MINIO_PASSWORD: ${MINIO_PASSWORD}

    networks:
      - tar-cloud

networks:
  tar-cloud:
    external: true
