- Infrastructure:
    - Homepage:
        icon: homepage.png
        href: /

    - Portainer:
        icon: portainer.png
        href: /portainer/

    - Uptime Kuma:
        icon: uptime-kuma.png
        href: /kuma/

    - Grafana:
        icon: grafana.png
        href: /grafana/

    - Prometheus:
        icon: prometheus.png
        href: /prometheus/

    - MinIO:
        icon: minio.png
        href: /minio/

- Platform:
    - PostgreSQL:
        icon: postgres.png
        href: /postgres/

    - MinIO:
        icon: minio.png
        href: /minio/

- Monitoring:
    - Prometheus:
        icon: prometheus.png
        href: /prometheus/

    - Grafana:
        icon: grafana.png
        href: /grafana/

- Applications:
    - Portfolio:
        icon: mdi-web

- Utilities:
    - URL Shortener:
        icon: mdi-link

    - QR Generator:
        icon: mdi-qrcode

    - Linktree:
        icon: mdi-account-network