---
title: Tar Cloud

theme: dark

color: slate

layout:
  Infrastructure:
    style: row
    columns: 3

  Platform:
    style: row
    columns: 3

  Monitoring:
    style: row
    columns: 2

  Applications:
    style: row
    columns: 2

  Utilities:
    style: row
    columns: 4

headerStyle: boxed

cardBlur: md

showStats: true
