services:
  minio:
    image: minio/minio:latest

    container_name: minio

    restart: unless-stopped

    command: server /data --console-address ":9001"

    ports:
      - "9001:9001"
      - "9002:9000"

    environment:
      MINIO_ROOT_USER: tar
      MINIO_ROOT_PASSWORD: change_this_password

    volumes:
      - /srv/data/minio:/data

    networks:
      - tar-cloud

networks:
  tar-cloud:
    external: true
