services:
  minio:
    image: minio/minio:latest

    container_name: minio

    restart: unless-stopped

    command: server /data --console-address ":9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}

    volumes:
      - /srv/data/minio:/data

    networks:
      - tar-cloud

networks:
  tar-cloud:
    external: true
