services:
  grafana:
    image: grafana/grafana-oss:latest

    container_name: grafana

    restart: unless-stopped

    env_file:
      - /srv/docker/env/tar-cloud.env

    environment:
      GF_SERVER_DOMAIN: node1
      GF_SERVER_ROOT_URL0: https://grafana.tarush.in
      GF_SERVER_SERVE_FROM_SUB_PATH: false

    volumes:
      - /srv/data/grafana:/var/lib/grafana

    networks:
      - tar-cloud

networks:
  tar-cloud:
    external: true
