services:
  grafana:
    image: grafana/grafana-oss:latest

    container_name: grafana

    restart: unless-stopped

    environment:
      GF_SERVER_DOMAIN: node1
      GF_SERVER_ROOT_URL: "http://node1/grafana/"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"

    volumes:
      - /srv/data/grafana:/var/lib/grafana

    networks:
      - tar-cloud

networks:
  tar-cloud:
    external: true
