services:
  grafana:
    image: grafana/grafana-oss:latest

    container_name: grafana

    restart: unless-stopped

    ports:
      - "3002:3000"

    volumes:
      - /srv/data/grafana:/var/lib/grafana

    networks:
      - tar-cloud

networks:
  tar-cloud:
    external: true
