services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx

    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - /srv/tar-cloud-infra/compose/nginx/conf.d:/etc/nginx/conf.d:ro
      - /srv/docker/nginx/html:/usr/share/nginx/html:ro