---
name: Deploy Tar Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Update Repository
        run: |
          cd /srv/tar-cloud-infra

          git fetch origin
          git reset --hard origin/main
          git clean -fd

      - name: Make Scripts Executable
        run: |
          cd /srv/tar-cloud-infra
          chmod +x scripts/*.sh

      - name: Deploy Infrastructure
        run: |
          cd /srv/tar-cloud-infra
          ./scripts/deploy.sh
